feat(messaging): Support Android 13+ notification permissions
capawesome-team/capacitor-firebase pull request #300
Opened 2023-01-10 12:51 UTC by CalumMurray

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] The changes have been tested successfully.
- [x] A changeset has been created (`npm run changeset`).

2023-01-10 14:14 UTC, robingenz commented
The permission `POST_NOTIFICATIONS` is only supported from Android 13 (API Level 33).
Capacitor 4 currently officially supports API level 32 (see [this comment](https://github.com/ionic-team/capacitor-plugins/issues/1116#issuecomment-1217720273)). API level 33 will be supported with Capacitor 5. For this reason, this PR has to wait until the release of Capacitor 5. In the meantime you can try to use the following plugin: https://github.com/hermitdemschoenenleben/capacitor-plugin-android-post-notifications-permission

2023-01-11 11:12 UTC, CalumMurray commented
Thanks very much for the quick response. I've updated to hopefully fix the build error for when it comes time to merge.

As noted in some other comments, the problem is that targeting API level 32 and using an Android 13 device means that the permission is immediately prompted on first open, meaning we can't prime the user for permissions as is best practice. Do you have any insight into why using a forked version with this permission might cause any issues with Capacitor 4 running on older and newer Androids? Is there some feature in Android 13 that is incompatible with Capacitor 4?

2023-01-11 11:40 UTC, robingenz commented
Unfortunately not. I would just give it a try and see if it works. I just can't merge this before Capacitor 5 is released because everyone would need to target API Level 33.

2023-04-26 09:37 UTC, CalumMurray commented
Done. It's been a while since I looked at this, so let me know if it still looks alright.

2023-04-28 05:50 UTC, robingenz commented on .changeset/three-llamas-appear.md
> +feat(messaging): Support Android 13+ notification permissions
```suggestion
feat(android): support Android 13+ notification permission
```

2023-04-28 05:56 UTC, robingenz requested changes
The last thing that is missing: we need to check the Android version and should only request the permission if it is >= Android 13.

Example: https://github.com/ionic-team/capacitor-plugins/blob/main/push-notifications/android/src/main/java/com/capacitorjs/plugins/pushnotifications/PushNotificationsPlugin.java#L78:L100

2023-04-28 05:56 UTC, robingenz commented on .changeset/three-llamas-appear.md
> +feat(messaging): Support Android 13+ notification permissions
```suggestion
feat(android): support Android 13+ notification permission
```

2023-04-30 18:14 UTC, closed without merging

2023-04-30 18:16 UTC, robingenz commented
@CalumMurray I just implemented it in another PR so I can finally test the Capacitor 5 version. Thanks for the PR anyway!