Update OAuthProviderHandler.swift
capawesome-team/capacitor-firebase pull request #538
Opened 2024-01-05 16:49 UTC by arstrasser

Very simple change to fix swapped link and signIn functions for oauth flow sign in.
Should resolve #524

Issue: 
Microsoft (and presumably other OAuth based sign in methods) were failing on iOS with a "No user signed in" error.
Swapping these functions as their names intend resolves the issue.

## Pull request checklist
Please check if your PR fulfills the following requirements:

- [X] The changes have been tested successfully.
- [ ] A changeset has been created (`npm run changeset`).
- [ ] I have read and followed the [pull request guidelines](https://capawesome.io/contributing/pull-requests/).

2024-01-06 09:42 UTC, robingenz requested changes
Thank you! Please create the missing changeset: `npm run changeset`

2024-01-10 14:31 UTC, arstrasser commented
Changeset created!

2024-01-10 17:00 UTC, robingenz requested changes

2024-01-10 17:00 UTC, robingenz commented on .changeset/fifty-eels-notice.md
> +Fix swapped link and signIn functions for oauth flow sign in
```suggestion
fix(ios): sign-in with oauth provider failed
```

2024-01-10 17:00 UTC, robingenz commented on .changeset/fifty-eels-notice.md
> +'@capacitor-firebase/authentication': minor
```suggestion
'@capacitor-firebase/authentication': patch
```

2024-01-10 17:01 UTC, robingenz approved these changes

2024-01-10 17:02 UTC, merged

2024-01-10 17:02 UTC, robingenz commented
@arstrasser Thank you for your contribution!