Issue 624 - addCollectionGroupSnapshotListener
capawesome-team/capacitor-firebase pull request #628
Opened 2024-05-21 18:14 UTC by svrznjak

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] The changes have been tested successfully. - **Only tested on Web and Android**
- [X] A changeset has been created (`npm run changeset`).
- [X] I have read and followed the [pull request guidelines](https://capawesome.io/contributing/pull-requests/).

Close #624

2024-05-21 19:29 UTC, robingenz requested changes

2024-05-21 19:29 UTC, robingenz commented on packages/firestore/README.md
Please revert the unnecessary changes in this file. Also, make sure to run `nm run docgen`.

2024-05-21 19:29 UTC, robingenz commented on .changeset/cold-zebras-pump.md
> +Added addCollectionGroupSnapshotListener to support snapshot listeners on collectionGroup query.
```suggestion
feat: add `addCollectionGroupSnapshotListener` method
```

2024-05-21 19:29 UTC, robingenz commented on packages/firestore/ios/Plugin/Classes/Options/AddCollectionGroupSnapshotListenerOptions.swift
You must add this file via XCode in order to register the file properly.

2024-05-21 19:29 UTC, robingenz commented on packages/firestore/ios/Plugin/FirebaseFirestorePlugin.swift
> +            call.reject("collectionId must be provided.")
```suggestion
            call.reject(errorReferenceMissing)
```

2024-05-21 19:29 UTC, robingenz commented on packages/firestore/src/definitions.ts
> +    options: GetCollectionGroupOptions,
```suggestion
    options: AddCollectionGroupSnapshotListenerOptions,
```

2024-05-21 19:29 UTC, robingenz commented on packages/firestore/src/definitions.ts
> + * @since TODO
```suggestion
 * @since 6.1.0
```

2024-05-22 15:04 UTC, svrznjak commented on packages/firestore/README.md
Oh, I did not notice prettier made changes before I committed changes. Now I reverted README.md, added an example of addCollectionGroupSnapshotListener, and then ran `npm run docgen`.

2024-05-23 07:44 UTC, robingenz approved these changes

2024-05-23 08:11 UTC, robingenz commented
Please fix the reported errors.

2024-06-18 05:49 UTC, closed without merging