Added verifyBeforeUpdateEmail method to Web, iOS, Android
capawesome-team/capacitor-firebase pull request #741
Opened 2024-10-22 01:16 UTC by ewwwgiddings

Pull request to handle this feature request:
https://github.com/capawesome-team/capacitor-firebase/issues/739

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] The changes have been tested successfully.
- [ ] A changeset has been created (`npm run changeset`).
- [ ] I have read and followed the [pull request guidelines](https://capawesome.io/contributing/pull-requests/).

2024-10-22 09:05 UTC, robingenz requested changes
This already looks very good. Please take a look at my comments.

2024-10-22 09:05 UTC, robingenz commented on packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthentication.java
> +    public void verifyBeforeUpdateEmail(FirebaseUser user, @NonNull String newEmail, @NonNull ActionCodeSettings actionCodeSettings, @NonNull Runnable callback) {
```suggestion
    public void verifyBeforeUpdateEmail(FirebaseUser user, @NonNull String newEmail, @NonNull ActionCodeSettings actionCodeSettings, @NonNull EmptyResultCallback callback) {
```

2024-10-22 09:05 UTC, robingenz commented on packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthentication.java
> +            );
```suggestion
            .addOnSuccessListener(unused -> callback.success())
            .addOnFailureListener(exception -> callback.error(exception));
```

I guess this method can throw an excpetion or not? If so, then we should handle this.

2024-10-22 21:53 UTC, ewwwgiddings commented
Thanks! Wasn't sure how far I was off with those.

I just implemented all your suggestions now and hit the re-request review button.

2024-10-22 22:14 UTC, ewwwgiddings commented
I also just updated the `newEmail` definition to what you liked and added an example in the README.

2024-10-23 05:28 UTC, robingenz commented on packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthentication.java
> +            );
Thanks for pointing that out. Feel free to create a new PR for the other methods. For now, just push that single change.

2024-10-23 05:32 UTC, robingenz requested changes

2024-10-23 05:32 UTC, robingenz commented on packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthenticationPlugin.java
> +            implementation.verifyBeforeUpdateEmail(user, newEmail, actionCodeSettings, () -> call.resolve());
You should also deal with the errors here (for example see `confirmVerificationCode`).

2024-10-23 10:40 UTC, ewwwgiddings commented
Just pushed a commit that adds the callback like the example method.

2024-10-23 11:59 UTC, ewwwgiddings commented
Just fixed the prettier issues as well. There were around 25 in unrelated files when using `--write` on the prettier command as a side note for some time in the future maybe.

2024-10-23 13:04 UTC, robingenz requested changes
These should be the last changes.

2024-10-23 13:04 UTC, robingenz commented on packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthenticationPlugin.java
> +            NonEmptyResultCallback callback = new NonEmptyResultCallback() {
```suggestion
            EmptyResultCallback callback = new EmptyResultCallback() {
```

2024-10-23 13:04 UTC, robingenz commented on packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/FirebaseAuthenticationPlugin.java
> +                }
```suggestion
                public void success() {
                    call.resolve();
                }
```

2024-10-23 13:37 UTC, egiddings-dealeron commented
Changes pushed

2024-10-23 14:10 UTC, robingenz commented
@ewwwgiddings Great, thank you! Two points remain before we can merge:
1. Create a changeset with the command`npm run changeset`. Please use the following text: ``feat: add `verifyBeforeUpdateEmail` method``
2. Test your implementation using this dev release:
	```
	npm i https://pkg.pr.new/capawesome-team/capacitor-firebase/@capacitor-firebase/authentication@741
	```

2024-10-23 14:52 UTC, ewwwgiddings commented
Pushed the changeset. As far as testing I'm currently unable to test anything but web with my setup. Eventually I'll get to a point I have all the environments set up but atm it's probably a couple months away.

2024-10-23 15:12 UTC, robingenz commented on packages/authentication/src/definitions.ts
> +  actionCodeSettings?: ActionCodeSettings;
```suggestion
  actionCodeSettings: ActionCodeSettings;
```

2024-10-23 15:13 UTC, robingenz approved these changes

2024-10-23 15:13 UTC, robingenz commented
@ewwwgiddings No problem. I will test it on Android and iOS before the next release. Thank you for your contribution!

2024-10-23 15:20 UTC, merged