fix(firestore): Prevent iOS crash caused by concurrency issue
capawesome-team/capacitor-firebase pull request #772
Opened 2024-12-11 03:22 UTC by TomCarey

Fixes #771

Wraps the `listenerRegistrationMap` in an actor to manage the reading and writing in a thread-safe way. It is necessary because `addCollectionSnapshotListener` and `addCollectionGroupSnapshotListener` dispatch a Task in order to build the constraints but then immediately write to the `listenerRegistrationMap` within that Task.

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] The changes have been tested successfully.
- [ ] A changeset has been created (`npm run changeset`).
- [ ] I have read and followed the [pull request guidelines](https://capawesome.io/contributing/pull-requests/).

2024-12-12 11:57 UTC, robingenz requested changes

2024-12-12 11:57 UTC, robingenz commented on .changeset/eleven-hornets-joke.md
> +fix(firestore): Prevent iOS crash caused by concurrency issue adding Collection Group Snapshot Listeners
```suggestion
fix(ios): prevent crash caused by concurrency issue
```

2024-12-12 11:57 UTC, robingenz commented on packages/firestore/ios/Plugin/FirebaseFirestore.swift
> +    @objc public func removeSnapshotListener(_ options: RemoveSnapshotListenerOptions) async {
```suggestion
    @objc public func removeSnapshotListener(_ options: RemoveSnapshotListenerOptions, completion: @escaping () -> Void) {
```

Please use a completion handler instead.

2024-12-12 11:57 UTC, robingenz commented on packages/firestore/ios/Plugin/FirebaseFirestore.swift
> +    @objc public func removeAllListeners() async {
```suggestion
    @objc public func removeAllListeners(completion: @escaping () -> Void) async {
```

Please use a completion handler instead.

2024-12-13 00:57 UTC, TomCarey commented on packages/firestore/ios/Plugin/FirebaseFirestorePlugin.swift
> -        super.removeAllListeners(call)
@robingenz Unfortunately the superclass also takes responsibility for `call.resolve()` which wouldn't be correct when we are asynchronously needing to remove our implementation listeners. I've added `self.eventListeners?.removeAllObjects()` which is the only feature of the super call we're interested in, but I thought you might want to weigh in.

2024-12-13 06:18 UTC, robingenz commented on packages/firestore/ios/Plugin/FirebaseFirestorePlugin.swift
> +            call.resolve()
```suggestion
            super.removeAllListeners(call)
```

2024-12-13 06:19 UTC, robingenz commented on packages/firestore/ios/Plugin/FirebaseFirestorePlugin.swift
> +        self.eventListeners?.removeAllObjects()
```suggestion
```

2024-12-15 20:34 UTC, TomCarey commented
@robingenz I _think_ there is an error introduced in your code suggestion. The dispatch queue of the capacitor bridge is internal so we can't dispatch work onto that queue. The event listeners of `CAPPlugin` are stored in a dictionary on that bridge queue. By calling super in the completion block we are running removeEventListeners in a different thread so there is a race condition where we might unsafely manipulate that dictionary. I'm not sure there is a simple solution here. It seems like it would be nice for capacitor to expose that queue. In theory though it would probably be "safer" to run the code in the way that I had it before where we didn't call `super.removeAllListeners`.

2024-12-16 20:16 UTC, TomCarey commented
Thanks @robingenz I've reverted that now.

2024-12-16 20:26 UTC, robingenz approved these changes
Thank you!

2024-12-16 21:44 UTC, merged