feat(authentication): add getIdTokenResult method
capawesome-team/capacitor-firebase pull request #786
Opened 2024-12-28 15:11 UTC by josephgodwinkimani

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] The changes have been tested successfully.
- [ ] A changeset has been created (`npm run changeset`).
- [ ] I have read and followed the [pull request guidelines](https://capawesome.io/contributing/pull-requests/).

2024-12-30 10:11 UTC, robingenz requested changes

2024-12-30 10:11 UTC, robingenz commented on packages/authentication/src/definitions.ts
> +  getIdTokenResult(options?: GetIdTokenOptions): Promise<GetIdTokenInfo>;
```suggestion
  getIdTokenResult(options?: GetIdTokenResultOptions): Promise<GetIdTokenResultResult>;
```

Interfaces should always be named like the method with a postfix (`Options` /  `Result`).

2024-12-30 10:11 UTC, robingenz commented on packages/authentication/src/definitions.ts
> +   *
```suggestion
   * 
   * @since 6.4.0
```

Add some version information.

2024-12-30 10:11 UTC, robingenz commented on packages/authentication/src/definitions.ts
> +   * Fetches the Firebase Auth ID Token and other helper properties for getting different data associated with the token as well as all the decoded payload claims for the currently signed-in user.
```suggestion
   * Returns a deserialized JSON Web Token (JWT) used to identify the user to a Firebase service.
```

2024-12-30 10:11 UTC, robingenz commented on packages/authentication/src/definitions.ts
> +  claims: ParsedToken;
```suggestion
  claims: [key: string]: unknown;
```

Keep it simple for now. We don't want to export external types.

2024-12-30 10:11 UTC, robingenz commented on packages/authentication/src/definitions.ts
> +export interface GetIdTokenInfo extends GetIdTokenResult {
```suggestion
export interface GetIdTokenInfo {
```

Just add a separate `token` property.

2024-12-31 09:28 UTC, robingenz requested changes

2024-12-31 09:28 UTC, robingenz commented on packages/authentication/src/definitions.ts
> +import { ParsedToken } from 'firebase/auth';
Please remove this import. It shouldn't be needed.

2025-01-03 08:17 UTC, robingenz requested changes
Please add the missing type `GetIdTokenResultOptions`, create a changeset (`npm run changeset`) and test your implementation.

2025-01-03 08:17 UTC, robingenz commented on packages/authentication/src/definitions.ts
> +export interface GetIdTokenInfo {
```suggestion
export interface GetIdTokenResultResult {
```

You should also rename the interface.

2025-01-03 18:41 UTC, josephgodwinkimani reviewed
add the missing type GetIdTokenResultOptions

2025-01-04 08:28 UTC, robingenz commented
@josephgodwinkimani Please create a changeset using `npm run changeset`.

2025-01-07 22:02 UTC, robingenz commented
Thank you, i will merge it this week.

2025-01-11 11:46 UTC, robingenz requested changes
I have just noticed that support for Android and iOS is missing. Please also add this since this plugin supports all 3 platforms.

2025-01-11 11:46 UTC, robingenz commented on .changeset/popular-cobras-camp.md
> +feat: add getIdTokenResult method
```suggestion
'@capacitor-firebase/authentication': minor
---

feat: add `getIdTokenResult()` method
```

2025-01-11 11:46 UTC, robingenz commented on packages/authentication/src/definitions.ts
> +  claims: Record<string, unknown>;
```suggestion
export interface GetIdTokenResultResult {
  /**
   * The authentication time formatted as a UTC string.
   *
   * This is the time the user authenticated (signed in) and not the time the token was refreshed.
   *
   * @since 6.4.0
   */
  authTime: string;
  /**
   * The ID token expiration time formatted as a UTC string. 
   *
   * @since 6.4.0
   */
  expirationTime: string;
  /** 
   * The ID token issuance time formatted as a UTC string. 
   *
   * @since 6.4.0
   */
  issuedAtTime: string;
  /**
   * The sign-in provider through which the ID token was obtained.
   *
   * @since 6.4.0
   */
  signInProvider: string | null;
  /**
   * The type of second factor associated with this session, provided the user was multi-factor
   * authenticated (eg. phone, etc).
   *
   * @since 6.4.0
   */
  signInSecondFactor: string | null;
  /**
   * The entire payload claims of the ID token including the standard reserved claims as well as
   * the custom claims.
   *
   * @since 6.4.0
   */
  claims: Record<string, unknown>;
```

2025-01-11 15:06 UTC, robingenz commented
@josephgodwinkimani Let me know as soon as you're done and I can review it again.

2025-01-18 10:06 UTC, josephgodwinkimani commented
> @josephgodwinkimani Let me know as soon as you're done and I can review it again.

@robingenz kindly review [my latest commit](https://github.com/capawesome-team/capacitor-firebase/pull/786/commits/d3057ca17128737977fa471948f49ed257c18ae5)

2025-01-18 16:23 UTC, robingenz commented
@josephgodwinkimani Please fix the build and lint errors and resolve the merge conflict.

2025-01-23 05:53 UTC, josephgodwinkimani commented
> @josephgodwinkimani Please fix the build and lint errors and resolve the merge conflict.

I can see a notice of the conflict in packages/authentication/ios/Plugin/FirebaseAuthenticationPlugin.m, but I am unable to identify the specific nature of the conflict.

2025-01-31 14:01 UTC, robingenz commented
@josephgodwinkimani I cannot merge this as long as you have this merge conflict. Just delete the `FirebaseAuthenticationPlugin.m` file. It no longer exists.

2025-02-01 09:50 UTC, robingenz commented
@josephgodwinkimani Your build failed. Please teste your changes before requesting a review.

2025-02-01 12:16 UTC, josephgodwinkimani commented
> @josephgodwinkimani Your build failed. Please teste your changes before requesting a review.

Thank you for pointing out the build failure. Unfortunately, I do not have access to an Apple-based machine to test iOS-specific changes locally. I recommend that someone with the appropriate hardware and environment verify the build. Please let me know if there's anything else I can assist with in resolving this issue.

2025-02-01 12:25 UTC, robingenz commented
@josephgodwinkimani Alright, I will take a look the iOS implementation. Please make sure to test the Android implementation.

2025-09-15 20:38 UTC, claptimes5 commented
I'm also in need of this feature. I've opened a new PR with a few additional commits that let `npm run verify` complete successfully and fix formatting issues. https://github.com/capawesome-team/capacitor-firebase/pull/913

if there is a better way for me to contribute, please let me know. Or if it's easier for you, please feel free to cherry-pick the commits.

2025-09-17 13:29 UTC, closed without merging