🚀 additional user info added
capawesome-team/capacitor-firebase pull request #81
Opened 2022-05-10 12:36 UTC by ssibrahimbas

## Pull request checklist

It is a fork created for the #30 issue.

What Has Been Done?

- The changes have been tested successfully.
- Created `AdditionalUserInfo.java` class.
- Edited `SignInResult` interface in `src/definitions.ts`.
- `AdditionalUserInfo` object is integrated in Android for all supporting providers.

2022-05-13 20:02 UTC, robingenz commented
Thank you! I will review it as soon as I have time.

2022-05-21 20:06 UTC, robingenz requested changes
Am I missing something or did you forget to commit the `AdditionalUserInfo` file?
Please adapt your implementation to the new interface (see my comments below).

Please also add an implementation for web and iOS.

2022-05-21 20:06 UTC, robingenz commented on packages/authentication/src/definitions.ts
> +  email?: string | null;
```suggestion
  isNewUser: boolean;
  username?: string;
  profile?: { [key: string]: any; };
```

It's best to follow the official JS SDK for this interface: https://firebase.google.com/docs/reference/js/auth.additionaluserinfo#properties

2022-05-22 09:23 UTC, ssibrahimbas commented
All right, I want to you to give me a little time. I Will take the following steps at a convenient time:

1. Update current system according to Firebase Documentation
2. Provide support for IOS and Web
3. Test step 1 and 2
4. Update pull request

I'II let you know!

2022-07-15 19:28 UTC, robingenz commented
Closed as inactive.

2022-07-15 19:28 UTC, closed without merging